### PR TITLE
Created simple burrow UI for iOS

### PR DESCRIPTION
**Pull request by AllTheSquares**
Edited the existing view so that if running on an iOS device it would provide a basic UI with a toggle switch that will allow the user to connect/disconnect from the VPN

In the iOS app, the toggle does not display if the user did not configure the VPN (or is using the app for the first time), and instead a button will show up to configure the VPN in Settings.

### CODE REVIEW

**Comment by karamassie** [comment]
@conradev -- can you fix the check issues here (you have the certificate needed) please

**Comment by karamassie** [comment]
(@ma1ted looked at code and helped here, so should otherwise be good to merge)

**Comment by conradev** [comment]
@AllTheSquares this will not work as a work, you need to move this to a branch in the main repo

**Comment by AllTheSquares** [comment]
How is that done again?

**Pull request closed without merging**
