### PR TITLE
Added Onboarding screen

### PR DESCRIPTION
**Pull request by AndromedaHelix**

### CODE REVIEW

**Review by Muirrum — CHANGES_REQUESTED** [review]
.DS_Store files should be added to the .gitignore and deleted from this PR

**Review by Muirrum — CHANGES_REQUESTED** [review]
Should rebase and add a body to all commits

(git rebase -i master and change all the commits to "reword")

**Comment by AndromedaHelix** [comment]
Just changed .gitignore

**Comment by Muirrum** [comment]
You need to modify your existing commits to match the git lint rules

**Comment by AndromedaHelix** [comment]
Okay, done

**Comment by AndromedaHelix** [comment]
Let me fix the git lint issues

**Comment by AndromedaHelix** [comment]
There we go, after 3 hours of getting a hang of git rebase, its done. Git lint passed and deleted .DS Store and added it to the .gitignore (sorry for the delay)

**Comment by Muirrum** [comment]
Great, thanks! Can someone who's more experienced in macOS look at the code contents?

**Comment by conradev** [comment]
> Although workflows from forks do not have access to sensitive data such as secrets, they can be an annoyance for maintainers if they are modified for abusive purposes.

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

We will need to move this branch from @AndromedaHelix's fork and into a branch in this repository

**Pull request merged**
